import joblib
import pandas as pd
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import QuizforMatric, QuizforInter
from .serializers import QuizforMatricSerializer, QuizforInterSerializer

# Load the pre-trained model
model_path = 'C:/Users/UsEr/fyp/django123/djangoauthapi1/quiz/nb_model.joblib'
model_path_inter = 'C:/Users/UsEr/fyp/django123/djangoauthapi1/quiz/naive_bayes_model.joblib'

X_train = pd.read_csv("C:/Users/UsEr/fyp/django123/djangoauthapi1/quiz/data_encoded.csv")

X_train = X_train.drop("Degree", axis = 1)
X_train = X_train.drop("Unnamed: 0", axis = 1)

try:
    model = joblib.load(model_path)
except FileNotFoundError:
    raise FileNotFoundError(f"Model file not found at path: {model_path}")

try:
    model_inter = joblib.load(model_path_inter)
except FileNotFoundError:
    raise FileNotFoundError(f"Model file not found at path: {model_path_inter}")


class QuizforMatricViewSet(APIView):
    def get(self, request, id=None):
        if id:
            quiz = get_object_or_404(QuizforMatric, id=id)
            serializer = QuizforMatricSerializer(quiz)
        else:
            quiz = QuizforMatric.objects.all()
            serializer = QuizforMatricSerializer(quiz, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = QuizforMatricSerializer(data=request.data)
        if serializer.is_valid():
            # Prepare data for model prediction
            new_data = pd.DataFrame({
                'Previous Percentage': [serializer.validated_data['percentage']],
                'Interest': [serializer.validated_data['question1']]
            })
            new_data_encoded = pd.get_dummies(new_data, columns=['Interest'], prefix='Interest')

            # Ensure column alignment with model's input features
            expected_columns = [
               "Previous Percentage",
        "Interest_Accounting",
        "Interest_Adventure Sports",
        "Interest_Aerospace Engineering",
        "Interest_Agriculture",
        "Interest_Animal Care",
        "Interest_Anthropology",
        "Interest_App Development",
        "Interest_Archaeology",
        "Interest_Architecture",
        "Interest_Art History",
        "Interest_Art Therapy",
        "Interest_Artificial Intelligence",
        "Interest_Arts",
        "Interest_Astronomy",
        "Interest_Astrophotography",
        "Interest_Astrophysics",
        "Interest_Aviation",
        "Interest_Back-end Development",
        "Interest_Baking",
        "Interest_Basketball",
        "Interest_Biology",
        "Interest_Bird Photography",
        "Interest_Birdwatching",
        "Interest_Botany",
        "Interest_Business",
        "Interest_Business Management",
        "Interest_Business Studies",
        "Interest_Calligraphy",
        "Interest_Carpentry",
        "Interest_Chemistry",
        "Interest_Civil Engineering",
        "Interest_Cloud Computing",
        "Interest_Coding",
        "Interest_Commerce",
        "Interest_Computer Engineering",
        "Interest_Computer Graphics",
        "Interest_Computer Networking",
        "Interest_Computer Programming",
        "Interest_Computer Science",
        "Interest_Cooking",
        "Interest_Cosmology",
        "Interest_Creative Coding",
        "Interest_Creative Writing",
        "Interest_Criminology",
        "Interest_Cryptography",
        "Interest_Culinary Arts",
        "Interest_Cultural Studies",
        "Interest_Cybersecurity",
        "Interest_Cycling",
        "Interest_Dance",
        "Interest_Dancing",
        "Interest_Data Analysis",
        "Interest_Data Analytics",
        "Interest_Data Science",
        "Interest_Database Management",
        "Interest_Digital Marketing",
        "Interest_Drama",
        "Interest_Drawing",
        "Interest_Economics",
        "Interest_Education",
        "Interest_Electrical Engineering",
        "Interest_Engineering",
        "Interest_Entrepreneurship",
        "Interest_Environmental Conservation",
        "Interest_Environmental Science",
        "Interest_Ethical Hacking",
        "Interest_Event Management",
        "Interest_Farming",
        "Interest_Fashion Design",
        "Interest_Fashion Merchandising",
        "Interest_Film Photography",
        "Interest_Film Studies",
        "Interest_Film-making",
        "Interest_Finance",
        "Interest_Financial Management",
        "Interest_Fine Arts",
        "Interest_Fishing",
        "Interest_Fitness Training",
        "Interest_Forensic Science",
        "Interest_Front-end Development",
        "Interest_Game Development",
        "Interest_Gaming",
        "Interest_Genealogy",
        "Interest_Genetics",
        "Interest_Geography",
        "Interest_Geology",
        "Interest_Graphic Design",
        "Interest_Graphic Novels",
        "Interest_Hiking",
        "Interest_History",
        "Interest_Human Resource Management",
        "Interest_Human Rights",
        "Interest_IT",
        "Interest_Information Technology",
        "Interest_Interior Design",
        "Interest_International Business",
        "Interest_International Relations",
        "Interest_Journalism",
        "Interest_Language Learning",
        "Interest_Linguistics",
        "Interest_Literature",
        "Interest_Marine Biology",
        "Interest_Market Research",
        "Interest_Marketing",
        "Interest_Martial Arts",
        "Interest_Mathematics",
        "Interest_Mechanical Engineering",
        "Interest_Media Studies",
        "Interest_Medicine",
        "Interest_Meditation",
        "Interest_Microbiology",
        "Interest_Mobile App Development",
        "Interest_Mobile Development",
        "Interest_Music",
        "Interest_Music Composition",
        "Interest_Music Production",
        "Interest_Network Administration",
        "Interest_Networking",
        "Interest_Nutrition",
        "Interest_Oceanography",
        "Interest_Operating Systems",
        "Interest_Organic Chemistry",
        "Interest_Organic Gardening",
        "Interest_Origami",
        "Interest_Painting",
        "Interest_Performing Arts",
        "Interest_Pet Care",
        "Interest_Philosophy",
        "Interest_Photography",
        "Interest_Physics",
        "Interest_Playing Chess",
        "Interest_Playing an Instrument",
        "Interest_Poetry",
        "Interest_Poetry Writing",
        "Interest_Political Economy",
        "Interest_Political Science",
        "Interest_Pottery",
        "Interest_Programming",
        "Interest_Psychology",
        "Interest_Public Health",
        "Interest_Public Speaking",
        "Interest_Reading",
        "Interest_Renewable Energy",
        "Interest_Retail Management",
        "Interest_Robotics",
        "Interest_Running",
        "Interest_Salsa Dancing",
        "Interest_Sculpting",
        "Interest_Sketching",
        "Interest_Soccer",
        "Interest_Social Media Management",
        "Interest_Sociology",
        "Interest_Software Development",
        "Interest_Software Engineering",
        "Interest_Software Testing",
        "Interest_Sports Management",
        "Interest_Sports Science",
        "Interest_Stand-up Comedy",
        "Interest_Statistics",
        "Interest_Supply Chain Management",
        "Interest_Sustainable Agriculture",
        "Interest_Swimming",
        "Interest_Theater",
        "Interest_Theater Arts",
        "Interest_Theater Production",
        "Interest_Traveling",
        "Interest_User Experience Design",
        "Interest_Video Game Development",
        "Interest_Volunteer Work",
        "Interest_Web Development",
        "Interest_Wilderness Survival",
        "Interest_Wildlife Biology",
        "Interest_Wildlife Conservation",
        "Interest_Wildlife Photography",
        "Interest_Woodworking",
        "Interest_Writing",
        "Interest_Yoga",
        "Interest_Zoology"
            ]
            new_data_encoded = new_data_encoded.reindex(columns=expected_columns, fill_value=0)

            # Make prediction
            predicted_degree = model.predict(new_data_encoded)
            print("Recommended Degree:", predicted_degree)

            # Save valid data to database
            serializer.save()
            return Response(predicted_degree, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class QuizforInterViewSet(APIView):
    def get(self, request, id=None):
        if id:
            quiz = get_object_or_404(QuizforInter, id=id)
            serializer = QuizforInterSerializer(quiz)
        else:
            quiz = QuizforInter.objects.all()
            serializer = QuizforInterSerializer(quiz, many=True)
        return Response(serializer.data)


    def post(self, request):
        serializer = QuizforInterSerializer(data=request.data)
        if serializer.is_valid():
            # Prepare data for model prediction
            new_data = pd.DataFrame({
                'Percentage': [serializer.validated_data['percentage']],
                'Interest': [serializer.validated_data['question1']],
                'Skills': [serializer.validated_data['question2']]
            })

            # One-hot encode 'Interest' and 'Skills' columns
            new_data_encoded = pd.get_dummies(new_data, columns=['Interest', 'Skills'], prefix=['Interest', 'Skills'])

            # Ensure column alignment with model's input features
#             expected_columns = [
#                 "Percentage",
#                 # List of all possible interests (from your model)
# "Interest_Agricultural Economics",
#     "Interest_Agricultural Engineering",
#     "Interest_Agroforestry",
#     "Interest_Agronomy",
#     "Interest_Algorithms",
#     "Interest_Anatomy",
#     "Interest_Animal Husbandry",
#     "Interest_Animal Nutrition",
#     "Interest_Animal Science",
#     "Interest_Animation",
#     "Interest_Artificial Intelligence",
#     "Interest_Behavioral Neuroscience",
#     "Interest_Botany",
#     "Interest_Broadcast Journalism",
#     "Interest_Broadcast Production",
#     "Interest_Business Analytics",
#     "Interest_Business Development",
#     "Interest_Business Management",
#     "Interest_Business Strategy",
#     "Interest_Child Development",
#     "Interest_Child Psychology",
#     "Interest_Civil Engineering",
#     "Interest_Clinical Neuropsychology",
#     "Interest_Clinical Psychology",
#     "Interest_Clinical Psychology Research",
#     "Interest_Cloud Architecture",
#     "Interest_Cloud Computing",
#     "Interest_Cognitive Neuroscience",
#     "Interest_Cognitive Psychology",
#     "Interest_Community Development",
#     "Interest_Community Sociology",
#     "Interest_Computer Graphics",
#     "Interest_Computer Networks",
#     "Interest_Computer Vision",
#     "Interest_Constitutional Law",
#     "Interest_Construction Management",
#     "Interest_Consumer Behavior",
#     "Interest_Consumer Psychology",
#     "Interest_Content Marketing",
#     "Interest_Content Marketing Strategy",
#     "Interest_Content Production",
#     "Interest_Content Writing",
#     "Interest_Corporate Finance",
#     "Interest_Counseling Psychology",
#     "Interest_Crime Prevention",
#     "Interest_Criminal Investigation",
#     "Interest_Criminal Justice",
#     "Interest_Criminal Justice Policy",
#     "Interest_Criminal Justice Reform",
#     "Interest_Criminal Law",
#     "Interest_Criminal Procedure",
#     "Interest_Criminal Profiling",
#     "Interest_Criminal Psychology",
#     "Interest_Criminology",
#     "Interest_Crop Management",
#     "Interest_Crop Science",
#     "Interest_Customer Relationship Management",
#     "Interest_Customer Service Management",
#     "Interest_Cyber Defense",
#     "Interest_Cybersecurity",
#     "Interest_Cybersecurity Governance",
#     "Interest_Data Analysis",
#     "Interest_Data Mining",
#     "Interest_Data Science",
#     "Interest_Data Structures",
#     "Interest_Database Administration",
#     "Interest_Database Development",
#     "Interest_Database Management",
#     "Interest_Database Systems",
#     "Interest_Deep Learning",
#     "Interest_Demography",
#     "Interest_Developmental Psychology",
#     "Interest_Digital Advertising",
#     "Interest_Digital Animation",
#     "Interest_Digital Art",
#     "Interest_Digital Content Creation",
#     "Interest_Digital Illustration",
#     "Interest_Digital Journalism",
#     "Interest_Digital Marketing",
#     "Interest_Digital Marketing Analytics",
#     "Interest_Digital Marketing Strategy",
#     "Interest_Digital Media Production",
#     "Interest_Digital Painting",
#     "Interest_Digital Photography",
#     "Interest_Digital Sculpture",
#     "Interest_Digital Storytelling",
#     "Interest_Digital Strategy",
#     "Interest_E-commerce",
#     "Interest_E-commerce Strategies",
#     "Interest_Entrepreneurial Finance",
#     "Interest_Entrepreneurship",
#     "Interest_Environmental Engineering",
#     "Interest_Environmental Law",
#     "Interest_Environmental Policy",
#     "Interest_Environmental Science",
#     "Interest_Environmental Sociology",
#     "Interest_Financial Analysis",
#     "Interest_Financial Management",
#     "Interest_Financial Modeling",
#     "Interest_Financial Planning",
#     "Interest_Financial Risk Management",
#     "Interest_Fine Arts",
#     "Interest_Forensic Psychology",
#     "Interest_Forensic Science",
#     "Interest_Front-end Development",
#     "Interest_Full-stack Development",
#     "Interest_Game Design",
#     "Interest_Game Development",
#     "Interest_Gender Studies",
#     "Interest_Genetics",
#     "Interest_Geographic Information Systems",
#     "Interest_Geotechnical Engineering",
#     "Interest_Graphic Design",
#     "Interest_Health Psychology",
#     "Interest_Horticulture",
#     "Interest_Human Resource Development",
#     "Interest_Human Rights Law",
#     "Interest_Hydraulic Engineering",
#     "Interest_Illustration",
#     "Interest_Industrial Psychology",
#     "Interest_Industrial-Organizational Psychology",
#     "Interest_Information Privacy",
#     "Interest_Information Retrieval",
#     "Interest_Information Security",
#     "Interest_Intellectual Property Law",
#     "Interest_Intellectual Property Rights",
#     "Interest_International Business Law",
#     "Interest_International Environmental Law",
#     "Interest_International Humanitarian Law",
#     "Interest_International Law",
#     "Interest_International Trade Law",
#     "Interest_Investment Analysis",
#     "Interest_Investment Banking",
#     "Interest_Journalism Ethics",
#     "Interest_Juvenile Justice",
#     "Interest_Law",
#     "Interest_Logistics Management",
#     "Interest_Machine Learning",
#     "Interest_Market Analysis",
#     "Interest_Market Research",
#     "Interest_Marketing Research",
#     "Interest_Marketing Strategy",
#     "Interest_Mass Communication",
#     "Interest_Media Ethics",
#     "Interest_Media Production",
#     "Interest_Mobile App Development",
#     "Interest_Mobile Development",
#     "Interest_Mobile Game Development",
#     "Interest_Multimedia Journalism",
#     "Interest_Natural Language Processing",
#     "Interest_Network Administration",
#     "Interest_Network Security",
#     "Interest_Neuroscience",
#     "Interest_Online Retail",
#     "Interest_Operations Management",
#     "Interest_Organizational Behavior",
#     "Interest_Organizational Psychology",
#     "Interest_Orthopedic Surgery",
#     "Interest_Pediatric Surgery",
#     "Interest_Photography",
#     "Interest_Plant Breeding",
#     "Interest_Plant Genetics",
#     "Interest_Plant Pathology",
#     "Interest_Plant Physiology",
#     "Interest_Plastic Surgery",
#     "Interest_Printmaking",
#     "Interest_Programming",
#     "Interest_Project Management",
#     "Interest_Public Relations",
#     "Interest_Public Relations Campaigns",
#     "Interest_Retail Management",
#     "Interest_Retail Operations",
#     "Interest_Rural Sociology",
#     "Interest_Sales Management",
#     "Interest_Sculpture",
#     "Interest_Search Engine Optimization",
#     "Interest_Social Development",
#     "Interest_Social Media Advertising",
#     "Interest_Social Media Management",
#     "Interest_Social Media Marketing",
#     "Interest_Social Media Strategy",
#     "Interest_Social Movements",
#     "Interest_Social Policy Analysis",
#     "Interest_Social Psychology",
#     "Interest_Social Research",
#     "Interest_Social Stratification",
#     "Interest_Social Welfare",
#     "Interest_Sociology of Education",
#     "Interest_Software Development",
#     "Interest_Software Engineering",
#     "Interest_Soil Science",
#     "Interest_Strategic Leadership",
#     "Interest_Strategic Management",
#     "Interest_Strategic Planning",
#     "Interest_Structural Analysis",
#     "Interest_Structural Engineering",
#     "Interest_Supply Chain Management",
#     "Interest_Supply Chain Optimization",
#     "Interest_Transportation Engineering",
#     "Interest_Transportation Planning",
#     "Interest_Urban Planning",
#     "Interest_Urban Sociology",
#     "Interest_Urbanization",
#     "Interest_Victim Advocacy",
#     "Interest_Victimology",
#     "Interest_Visual Arts",
#     "Interest_Water Quality Management",
#     "Interest_Water Resource Management",
#     "Interest_Water Resources Engineering",
#     "Interest_Water Resources Management",
#     "Interest_Web Application Development",
#     "Interest_Web Design",
#     "Interest_Web Development",
#     "Interest_Youth Justice"
#                 # Add all other interests...
#                 # List of all possible skills (if applicable)
#                  "Skills_3D Animation",
#     "Skills_3D Modeling",
#     "Skills_3D Modelling",
#     "Skills_Agribusiness Management",
#     "Skills_Agricultural Economics",
#     "Skills_Agricultural Extension",
#     "Skills_Agricultural Mechanization",
#     "Skills_Agricultural Sociology",
#     "Skills_Agronomy",
#     "Skills_Algorithm Design",
#     "Skills_Andriod Development",
#     "Skills_Android Development",
#     "Skills_Android Development",
#     "Skills_Android Development67",
#     "Skills_Animal Nutrition",
#     "Skills_Animation",
#     "Skills_Animation",
#     "Skills_Artificial Intelligence",
#     "Skills_Artificial Neural Networks",
#     "Skills_Artistic Expression",
#     "Skills_Backend Development",
#     "Skills_Behavioral Analysis",
#     "Skills_Behavioral Psychology",
#     "Skills_Biology Research",
#     "Skills_Body Analysis",
#     "Skills_Brand Development",
#     "Skills_Brand Management",
#     "Skills_Broadcast News Reporting",
#     "Skills_Business Development",
#     "Skills_Business Planning",
#     "Skills_Business Strategy",
#     "Skills_Ceramics",
#     "Skills_Change Management",
#     "Skills_Channel Management",
#     "Skills_Character Animation",
#     "Skills_Character Design",
#     "Skills_Character Rigging",
#     "Skills_Child Psychology",
#     "Skills_Child Therapy",
#     "Skills_Civil Engineering Design",
#     "Skills_Client Relationship Management",
#     "Skills_Climate Change Law",
#     "Skills_Cloud Computing Platforms",
#     "Skills_Cognitive Neuroscience",
#     "Skills_Cognitive Psychology",
#     "Skills_Commercial Law",
#     "Skills_Community Development",
#     "Skills_Community Engagement",
#     "Skills_Community Engagement",
#     "Skills_Community Outreach",
#     "Skills_Community Planning",
#     "Skills_Community Policing",
#     "Skills_Complaint Handling",
#     "Skills_Computer Vision",
#     "Skills_Concept Art",
#     "Skills_Concept Design",
#     "Skills_Conservation Biology",
#     "Skills_Constitutional Law",
#     "Skills_Construction Engineering",
#     "Skills_Construction Management",
#     "Skills_Consumer Behavior",
#     "Skills_Consumer Behavior Analysis",
#     "Skills_Consumer Insights",
#     "Skills_Content Creation",
#     "Skills_Content Management",
#     "Skills_Content Marketing",
#     "Skills_Content Optimization",
#     "Skills_Content Planning",
#     "Skills_Content Strategy",
#     "Skills_Contract Law",
#     "Skills_Copyright Law",
#     "Skills_Corporate Communication",
#     "Skills_Corporate Strategy",
#     "Skills_Corrections Management",
#     "Skills_Cosmetic Surgery",
#     "Skills_Crime Analysis",
#     "Skills_Crime Scene Analysis",
#     "Skills_Criminal Behavior Analysis",
#     "Skills_Criminal Investigation",
#     "Skills_Criminal Justice",
#     "Skills_Criminal Profiling",
#     "Skills_Criminalistics",
#     "Skills_Criminological Theory",
#     "Skills_Crop Protection",
#     "Skills_Cross-platform Development",
#     "Skills_Customs Law",
#     "Skills_Cybersecurity",
#     "Skills_Data Analysis",
#     "Skills_Data Analytics",
#     "Skills_Data Protection",
#     "Skills_Data Science",
#     "Skills_Data Security",
#     "Skills_Data Structures",
#     "Skills_Data Visualization",
#     "Skills_Data Warehousing",
#     "Skills_Database Administration",
#     "Skills_Database Design",
#     "Skills_Database Management",
#     "Skills_Database Management Systems",
#     "Skills_Database Optimization",
#     "Skills_Database Systems",
#     "Skills_Decision Making",
#     "Skills_Deep Learning",
#     "Skills_Deep Reinforcement Learning",
#     "Skills_Developmental Psychology",
#     "Skills_Digital Editing",
#     "Skills_Digital Painting",
#     "Skills_Disease Management",
#     "Skills_Documentary Production",
#     "Skills_Early Childhood Education",
#     "Skills_Email Marketing",
#     "Skills_Employee Motivation",
#     "Skills_Employee Relations",
#     "Skills_Employee Training",
#     "Skills_Environmental Impact Assessment",
#     "Skills_Environmental Remediation",
#     "Skills_Etching",
#     "Skills_Ethical Hacking",
#     "Skills_Experimental Design",
#     "Skills_Feminist Theory",
#     "Skills_Film Editing",
#     "Skills_Financial Analysis",
#     "Skills_Financial Management",
#     "Skills_Financial Modeling",
#     "Skills_Financial Planning",
#     "Skills_Financial Reporting",
#     "Skills_Firewall Configuration",
#     "Skills_Forensic Psychology",
#     "Skills_Forensic Psychology",
#     "Skills_Forensic Science",
#     "Skills_Foundation Design",
#     "Skills_Front-end Development",
#     "Skills_Frontend Development",
#     "Skills_Game Design",
#     "Skills_Game Programming",
#     "Skills_Gender Studies",
#     "Skills_Genetic Engineering",
#     "Skills_Genomic Analysis",
#     "Skills_Geological Mapping",
#     "Skills_Geological Surveying",
#     "Skills_Geotechnical Engineering",
#     "Skills_Geotechnical Investigation",
#     "Skills_Graphic Design",
#     "Skills_Group Dynamics",
#     "Skills_Health Behavior",
#     "Skills_Highway Design",
#     "Skills_Human Resources Management",
#     "Skills_Human Rights Law",
#     "Skills_Humanitarian Law",
#     "Skills_Hydrological Modeling",
#     "Skills_Hydrology",
#     "Skills_IT Risk Management",
#     "Skills_IT Security",
#     "Skills_Illustration Techniques",
#     "Skills_Image Processing",
#     "Skills_Incident Response",
#     "Skills_Influencer Collaboration",
#     "Skills_Influencer Marketing",
#     "Skills_Infrastructure Design",
#     "Skills_International Business Law",
#     "Skills_International Business Transactions",
#     "Skills_International Criminal Law",
#     "Skills_International Criminal Law",
#     "Skills_International Human Rights Law",
#     "Skills_International Humanitarian Law",
#     "Skills_International Refugee Law",
#     "Skills_International Trade Law",
#     "Skills_Inventory Control",
#     "Skills_Inventory Management",
#     "Skills_Investment Analysis",
#     "Skills_Investment Management",
#     "Skills_Investment Strategies",
#     "Skills_Journalism",
#     "Skills_Journalism Ethics",
#     "Skills_Leadership",
#     "Skills_Leadership Development",
#     "Skills_Legal Analysis",
#     "Skills_Legal Research",
#     "Skills_Legal Writing",
#     "Skills_Livestock Management",
#     "Skills_Livestock Nutrition",
#     "Skills_Logistics Management",
#     "Skills_Logistics Management",
#     "Skills_Logistics Planning",
#     "Skills_Machine Learning",
#     "Skills_Machine Learning Algorithms",
#     "Skills_Market Analysis",
#     "Skills_Market Research",
#     "Skills_Marketing Analytics",
#     "Skills_Marketing Analytics",
#     "Skills_Media Law",
#     "Skills_Media Literacy",
#     "Skills_Media Relations",
#     "Skills_Memory Research",
#     "Skills_Merchandising",
#     "Skills_Mind Read",
#     "Skills_Mind Read",
#     "Skills_Natural Language Processing",
#     "Skills_Natural Resources Law",
#     "Skills_Negotiation Skills",
#     "Skills_Neonatal Surgery",
#     "Skills_Network Administration",
#     "Skills_Network Defense",
#     "Skills_Network Security",
#     "Skills_Neural Network Design",
#     "Skills_Neural Networks",
#     "Skills_Neuropsychological Assessment",
#     "Skills_Neuropsychology",
#     "Skills_News Anchoring",
#     "Skills_News Reporting",
#     "Skills_Online Advertising",
#     "Skills_Online Marketing",
#     "Skills_Online News Reporting",
#     "Skills_Online Reporting",
#     "Skills_Operations Management",
#     "Skills_Organizational Behavior",
#     "Skills_Orthopedic Trauma Surgery",
#     "Skills_PPC Advertising",
#     "Skills_Painting",
#     "Skills_Patent Law",
#     "Skills_Penetration Testing",
#     "Skills_Photo Editing",
#     "Skills_Photography Editing",
#     "Skills_Photojournalism",
#     "Skills_Photomanipulation",
#     "Skills_Phycological Profiling",
#     "Skills_Physiological Profiling",
#     "Skills_Physiology",
#     "Skills_Plant Breeding",
#     "Skills_Plant Genetics",
#     "Skills_Plant Nutrition",
#     "Skills_Plant Pathology",
#     "Skills_Plant Physiology",
#     "Skills_Podcasting",
#     "Skills_Population Studies",
#     "Skills_Portfolio Management",
#     "Skills_Project Management",
#     "Skills_Project Planning",
#     "Skills_Psychological Assessment",
#     "Skills_Psychological Profiling",
#     "Skills_Public Administration",
#     "Skills_Public International Law",
#     "Skills_Quantitative Analysis",
#     "Skills_Race Relations",
#     "Skills_Radio Broadcasting",
#     "Skills_Reconstructive Procedures",
#     "Skills_Reconstructive Surgery",
#     "Skills_Reinforcement Learning",
#     "Skills_Remote Sensing",
#     "Skills_Restorative Justice",
#     "Skills_Rural Development",
#     "Skills_SEO Strategy",
#     "Skills_SQL",
#     "Skills_SQL Programming",
#     "Skills_Screen Printing",
#     "Skills_Scriptwriting",
#     "Skills_Search Engine Marketing",
#     "Skills_Search Engine Optimization",
#     "Skills_Security Analysis",
#     "Skills_Security Management",
#     "Skills_Social Change",
#     "Skills_Social Ecology",
#     "Skills_Social Media Advertising",
#     "Skills_Social Media Management",
#     "Skills_Social Media Marketing",
#     "Skills_Social Planning",
#     "Skills_Sociological Theory",
#     "Skills_Software Architecture",
#     "Skills_Software Testing",
#     "Skills_Soil Conservation",
#     "Skills_Soil Science",
#     "Skills_Spinal Surgery",
#     "Skills_Startup Development",
#     "Skills_Startup Management",
#     "Skills_Statistical Analysis",
#     "Skills_Storyboarding",
#     "Skills_Strategic Planning",
#     "Skills_Strategic Sales",
#     "Skills_Strategic Sales Planning",
#     "Skills_Structural Design",
#     "Skills_Supply Chain Management",
#     "Skills_Supply Chain Optimization",
#     "Skills_Sustainable Development",
#     "Skills_System Administration",
#     "Skills_Team Leadership",
#     "Skills_Team Management",
#     "Skills_Television Broadcasting",
#     "Skills_Television Directing",
#     "Skills_Television Production",
#     "Skills_Temperature Check",
#     "Skills_Text Mining",
#     "Skills_Therapeutic Techniques",
#     "Skills_Trade Law",
#     "Skills_Trade Policy",
#     "Skills_Trademark Law",
#     "Skills_Traffic Engineering",
#     "Skills_Training and Development",
#     "Skills_Transportation Engineering",
#     "Skills_Transportation Engineering",
#     "Skills_Transportation Planning",
#     "Skills_Typography",
#     "Skills_UI/UX Design",
#     "Skills_Unity Game Engine",
#     "Skills_Urban Regeneration",
#     "Skills_Urban Studies",
#     "Skills_User Experience Design",
#     "Skills_User Interface Design",
#     "Skills_Vector Art",
#     "Skills_Venture Capital",
#     "Skills_Victim Advocacy",
#     "Skills_Video Editing",
#     "Skills_Video Production",
#     "Skills_Virtualization",
#     "Skills_Water Quality Management",
#     "Skills_Water Resource Management",
#     "Skills_Water Treatment",
#     "Skills_Wealth Management",
#     "Skills_Web Analytics",
#     "Skills_Web Application Development",
#     "Skills_Web Development",
#     "Skills_Youth Counseling",
#     "Skills_Youth Outreach",
#     "Skills_Youth Rehabilitation",
#     "Skills_podcasting"
#                 # Add all other skills...
#             ]
            new_data_encoded = new_data_encoded.reindex(columns=X_train.columns, fill_value=0)

            # Make prediction using the loaded model
            predicted_degree = model_inter.predict(new_data_encoded)
            print("Recommended Degree:", predicted_degree)
       

            # Save valid data to database
            serializer.save()

            # Return the predicted degree as a response
            return Response(predicted_degree, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)