# Generated by Django 5.0.3 on 2024-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizforMatric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.1')),
                ('question2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.2')),
                ('question3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.3')),
                ('question4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.4')),
                ('question5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.5')),
                ('question6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.6')),
                ('question7', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.7')),
                ('question8', models.CharField(blank=True, max_length=50, null=True, verbose_name='Question No.8')),
            ],
        ),
    ]
