# Generated by Django 5.0 on 2024-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizformatric",
            name="question3",
        ),
        migrations.RemoveField(
            model_name="quizformatric",
            name="question4",
        ),
        migrations.RemoveField(
            model_name="quizformatric",
            name="question5",
        ),
        migrations.RemoveField(
            model_name="quizformatric",
            name="question6",
        ),
        migrations.RemoveField(
            model_name="quizformatric",
            name="question7",
        ),
        migrations.RemoveField(
            model_name="quizformatric",
            name="question8",
        ),
        migrations.AddField(
            model_name="quizformatric",
            name="percentage",
            field=models.FloatField(default=1, verbose_name="Percentage"),
            preserve_default=False,
        ),
    ]
