# Generated by Django 5.0 on 2024-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quizforinter"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizforinter",
            name="question3",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Question No.3"
            ),
        ),
    ]
