# Generated by Django 5.0.3 on 2024-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizforinter_question3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizforinter',
            name='question3',
        ),
        migrations.AddField(
            model_name='quizforinter',
            name='percentage',
            field=models.FloatField(default=1, verbose_name='Percentage'),
            preserve_default=False,
        ),
    ]
